name: 'Install Lokalise CLI'
runs:
  using: "composite"
  steps:
  - name: Install CLI
    run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
    shell: bash
  - name: Add to PATH
    run: echo "$(pwd)/bin" >> $GITHUB_PATH
    shell: bash
