name: 'Upload strings'
description: 'Uploads source strings to Lokalise for the current branch'
inputs:
  localization-file:
    description: The path to the source localization file.
    required: true
runs:
  using: "composite"
  steps:
  - uses: YousicianGit/LokaliseActions/install-cli@main
  - name: Update translatios
    run: ${{ github.action_path }}/upload_strings.sh ${{ inputs.localization-file }} ${{ github.head_ref || github.ref_name }}
    shell: bash
